### ISSUE TITLE
When hide Cap (Bottle 2) and then show it, this is located in the origin

### ISSUE THREAD

**Issue by Oxervision** [kostex/blenderscripts#1]
macOS 10.13.6 & Blender v2.80.58, KTX_Bottle_2.py v1.1.1
Hi, the fisrt thanks for the addon!
Like title says, if you hide the cap and then you show it, this is located in the origin, I think it should be in the top of the bottle.
Thanks in advance, 
Greetings,

Óscar
![Cap in origin](https://user-images.githubusercontent.com/46649474/56893536-460c9300-6a83-11e9-8748-95702352d60c.jpg)

**Comment by kostex** [comment]
Hi Óscar,

I’m aware of the issue, but until now this is still a bug in Blender 2.80, not in my script.. if you look at the coordinates of the cap, it will state the correct position.
If you enter edit mode of the cap and then back to object mode, you will see it snaps into the right place.. as soon as the blender bug is fixed, my script will be updated or it will work without doing a thing ;-)

But I will check if there's a shortcut to get it working without relying on blender again.


Greets,
Roel
![Screenshot 2019-04-29 at 17 16 53](https://user-images.githubusercontent.com/11047825/56910510-a5c66680-6aa2-11e9-807b-d6643aa61983.png)

**Comment by Oxervision** [comment]
Thanks for the reply!!

**Comment by kostex** [comment]
please check latest version of blender and addon.. only a couple of hours ago they've changed some other related code too, so you'll really need the newest blender build (viewport hiding/showing objects code has changed in blender)
https://git.blender.org/gitweb/gitweb.cgi/blender.git/commit/b1af682001596fb2943dca3e39a256be71637906
